### PR TITLE
Update INR symbol site-utils.js

### PR DESCRIPTION
**Pull request by selvassn**
Update of INR symbol (₹) is required else it will fail in the processprice function

### CODE REVIEW

**Comment by dylants** [comment]
Thanks for the offer to contribute! It looks like there's some failures in the unit tests after this change was made, as well as some e2e tests failing because of site changes. Can you try and fix the unit tests? I'll attempt to fix the e2e tests soon if they continue...

**Comment by selvassn** [comment]
Hi,

Can you give permisseion to push to your repo? I am getting below error.

remote: Permission to dylants/price-finder.git denied to selvassn.
fatal: unable to access 'https://github.com/dylants/price-finder.git/': The requested URL returned error: 403

Regards,
Selva

________________________________

**Comment by selvassn** [comment]
Can you give permisseion to push to your repo? I am getting below error.

remote: Permission to dylants/price-finder.git denied to selvassn.
fatal: unable to access 'https://github.com/dylants/price-finder.git/': The requested URL returned error: 403

**Comment by dylants** [comment]
The permission is correct, you shouldn't be pushing to dylants, but instead to your repository's fork of this code which will then be merged in via this pull request. Does that make sense? I believe you have already done this once, to create the initial pull request. You must have forked the repo, made a commit, then pushed it to the remote (which would be selvassn/patch-1). You would just make another change locally and push that commit to your repo to update this pull request.

**Comment by dylants** [comment]
Great! Looks like the unit tests are passing now. The e2e tests are failing still. Separately, I've fixed the e2e tests (https://github.com/dylants/price-finder/pull/131) and merged those changes to the master branch.

If you rebase your branch off master, it should pick up the e2e test fixes which should then allow all checks to pass. Once all the checks pass, I can merge these changes in.

**Comment by dylants** [comment]
Closing because of inactivity. Please re-open if needed.

**Pull request closed without merging**
