### PR TITLE
NewEgg support

### PR DESCRIPTION
**Pull request by rajkumarpb**
Added Support for NewEgg with test cases.

### CODE REVIEW

**Comment by dylants** [comment]
Looks great, thanks for your work in adding this new feature!

**Comment by rajkumarpb** [comment]
I don't know the dynamics of US Shopping much, but if you can create a milestone kinda thing with list of sites to add, I'll be eager to do some work in this plugin. I just like to see this gets expanded instead of getting restricted to one geographical location.

**Comment by dylants** [comment]
@rajkumarpb Thanks for the offer to help!  I don't have a list at this time, but I'd check the issues list or add features for sites that you'd like to include.  I think the newegg support added here is great and will help future users.

**Comment by rajkumarpb** [comment]
Sure @dylants . Please let me know if you need any help in drafting the list.

**Pull request merged**
