### PR TITLE
Infibeam Support Commit

### PR DESCRIPTION
**Pull request by rajkumarpb**
Sorry for the trouble @dylants . Since I lost touch with git couple of years ago, I'm kinda screw things up with git. Since I can't able to re-base, I'm moving all those changes in a single commit!

### CODE REVIEW

**Comment by dylants** [comment]
This is great!  Sorry about the git rebase/squash problems, but glad you were able to get this all fixed, really looks good!

I completely understand the reasoning around changing the testcase to fit the inclusion of `R` as a currency check.  I'm with you in that I don't think we'll get prices with an `R` in them that's not INR, but we may.  If this is the case, an issue can be opened and we can fix it then.  Until then, I think this is perfectly reasonable approach.

I also have to apologize for the upper case / lower case request.  After looking through the code I missed the `toLowerCase()` at the beginning of the function definition.  So it would have worked all along!  But it works now, so we'll move forward.  Sorry about that!

**Comment by rajkumarpb** [comment]
Regarding that lowercase, I completely forgot it man! It happens.

As you said, until we get an open issue, I don't think using R as currency will have any impact on test case!

**Comment by dylants** [comment]
@rajkumarpb Thanks for your hard work in putting this all together!  I've added you as a collaborator to this project.  One benefit is not having to fork the repo, so any branches/pull requests are local to this repository.  Thanks again!

**Comment by rajkumarpb** [comment]
@dylants That's cool man! Thanks.

**Comment by dylants** [comment]
@rajkumarpb I'm sorry if this gives the wrong impression, but after reading more about GitHub's lack of fine grained security and it's "all or nothing" permissions, I have to admit I'm a little uncomfortable with the collaborator roles that I had given out recently.  There just doesn't seem to be a middle ground between no access and complete access.  I'm sure this is fine for some, but for me, it makes me feel vulnerable for work that is so important to me.  So unfortunately I'm going to remove the collaborators.  I really hope that this does not stop you from contributing, and I will certainly provide attribution when you do so.  I'm happy to work with everyone and will continue to add features requested and accept features as they come.  Thank you again for your contributions so far.

**Comment by rajkumarpb** [comment]
@dylants Does this have something to do with my last commit? Anyways I understand what you are trying to say. So no problem!

**Pull request merged**
