### PR TITLE
TravisCI status to use master branch

### PR DESCRIPTION
**Pull request by dylants**
Specify the master branch in the TravisCI status image.

### CODE REVIEW

**Comment by rajkumarpb** [comment]
Does this mean the branches will not be tested with Travis?

**Comment by dylants** [comment]
No it's just the status image in the readme

**Comment by rajkumarpb** [comment]
Ok! By the way, if you looks at last few flipkart branch builds, even few older test cases failed, like amazon and price-minister! I guess they block it somehow?

**Comment by dylants** [comment]
This should no longer be an issue

**Pull request merged**
