### PR TITLE
handle alternative priceminister url

### PR DESCRIPTION
**Pull request by Shuunen**

### CODE REVIEW

**Comment by Shuunen** [comment]
@dylants waiting for your approval :)

**Comment by dylants** [comment]
Looks good, thanks for the update!

**Comment by dylants** [comment]
Actually, sorry, I didn't notice that this was merged into master.  We're using the `dev` branch for development.  Do you mind submitting the pull request to that branch instead?  I'm going to try to back that out of master to avoid merge conflicts (master is the latest release of the library).

**Comment by Shuunen** [comment]
ok i'm on it

**Comment by Shuunen** [comment]
Done :) https://github.com/dylants/price-finder/pull/27

**Comment by dylants** [comment]
Hey @Shuunen, just wanted to let you know that I'm planning on removing the `dev` branch and going back to a simple `master` main branch.  There's another pull request that wants to merge to `master`, so it seems it's more confusing to others to have these two branches than any benefit from having both.  So master branch it is! :smile:

**Comment by Shuunen** [comment]
Good it will be simpler yes :)

**Pull request merged**
